language:
  - cpp
branches:
  only:
    - master

matrix:
  fast_finish: true
  include:
    - os: osx
      osx_image: xcode10.2
      python: 3.4
  addons:
    homebrew:
      packages:
      - doxygen
      update: true

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test