language:
  - cpp
branches:
  only:
    - master
    - conan

matrix:
  fast_finish: true
  include:
    - os: osx
      osx_image: xcode10.2
      python: 3.4
      sudo: true

    - os: osx
      osx_image: xcode10    
      python: 3.4
      env:
        - MATRIX_EVAL="brew install gcc@7 && CC=gcc-7 && CXX=g++-7"
      
    - os: linux
      dist: xenial
      sudo: true      
      compiler:
        - g++      
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - doxygen
            - doxygen-doc
            - doxygen-latex
            - doxygen-gui
            - graphviz
            - cmake	  
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      dist: xenial
      before_install:
	- export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH
      sudo: true
      addons:
        apt:
          packages:
            - doxygen
            - doxygen-doc
            - doxygen-latex
            - doxygen-gui
            - graphviz
            - cmake	  
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
    - eval "${MATRIX_EVAL}"

script:
    - chmod +x .travis/build.sh
    - .travis/build.sh

deploy:
  if: os = linux
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master