linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   services:
     - docker
     
osx: &osx
   os: osx
   language: generic

branches:
  only:
    - master
    - /^(?stable).*$/    

matrix:
  fast_finish: true
  include:
    - <<: *linux
      env:
	- CONAN_GCC_VERSIONS=7
	- CONAN_DOCKER_IMAGE=conanio/gcc7
	- BUILD_PACKAGE="YES"
    - <<: *linux
      env:
	- CONAN_GCC_VERSIONS=8
	- CONAN_DOCKER_IMAGE=conanio/gcc8
	- BUILD_PACKAGE="YES"
    - <<: *linux
      env:
	- CONAN_GCC_VERSIONS=9
	- CONAN_DOCKER_IMAGE=conanio/gcc9
	- BUILD_PACKAGE="YES"
    - <<: *linux
      env:
	- CONAN_CLANG_VERSIONS=7.0
	- CONAN_DOCKER_IMAGE=conanio/clang7
	- BUILD_PACKAGE="YES"
    - <<: *linux
      env:
	- CONAN_CLANG_VERSIONS=8
	- CONAN_DOCKER_IMAGE=conanio/clang8
	- BUILD_PACKAGE="YES"
    - <<: *osx
      osx_image: xcode10.2 
      env:
	- CONAN_APPLE_CLANG_VERSIONS=10.0
	- BUILD_PACKAGE="YES"
    - <<: *osx
      osx_image: xcode10.3
      env:
	- CONAN_APPLE_CLANG_VERSIONS=10.0
	- BUILD_PACKAGE="YES"

before_install:
  - eval "${MATRIX_EVAL}"     

install:
  if: ${BUILD_PACKAGE} = "YES"
    - chmod +x .travis/install.sh
    - ./.travis/install.sh
  if: ${BUILD_PACKAGE} = "YES"
    - pip install conan
    - conan user    

script:
  if: ${TEST_BUILD} = "YES"
    - chmod +x .travis/build.sh    
    - .travis/build.sh
  if: ${BUILD_PACKAGE} = "YES"
    - chmod +x .travis/run.sh
    - ./.travis/run.sh 

deploy:
  if: ${BUILD_DOCS} = "YES"
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master