language:
  - cpp
branches:
  only:
    - master

matrix:
  fast_finish: true
  include:
    - os: osx
      osx_image: xcode10.2
      language:
        - cpp      
      addons:
        homebrew:
	  packages:
          - doxygen
          - doxygen-doc
          - doxygen-latex
          - doxygen-gui
          - graphviz
          - cmake	  
          update: true      

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION
  - source activate test-env

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master