dist: trusty
sudo: true
language:
  - cpp
compiler:
  - g++


branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
      - cmake

before_script:
  - mkdir build
  - cd build
  - cmake ..
  
script:
  - make
  - make test
  - cd ..
  - doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master