dist: xenial
sudo: true
language:
  - cpp
compiler:
  - g++

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - doxygen
            - doxygen-doc
            - doxygen-latex
            - doxygen-gui
            - graphviz
            - cmake	  
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: osx
      osx_image: xcode10.2
      addons:
        homebrew:
	  packages:
          - doxygen
          - doxygen-doc
          - doxygen-latex
          - doxygen-gui
          - graphviz
          - cmake	  
          update: true      

before_install:
    - eval "${MATRIX_EVAL}"

install:
  - if "$TRAVIS_OS_NAME" == "osx"
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION
  - source activate test-env

script:
  - wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
  - sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
  - sudo sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list'
  - sudo sh -c 'echo deb https://apt.repos.intel.com/ipp all main > /etc/apt/sources.list.d/intel-ipp.list'
  - sudo apt-get update
  - sudo apt-get install intel-mkl-2019.3-062
  - sudo apt-get install intel-ipp-2019.3-062
  - source /opt/intel/mkl/bin/mklvars.sh intel64
  - source /opt/intel/ipp/bin/ippvars.sh intel64 linux
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
  - cd ..
  - doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master