branches:
  only:
    - /^stable\/.*$/

matrix:
  include:
    - os: linux
      dist: xenial
      language: python
      python: "3.7"
      sudo: true      
      compiler:
        - g++      
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - doxygen
            - doxygen-doc
            - doxygen-latex
            - doxygen-gui
            - graphviz
            - cmake	  
            - g++-7
      env:
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"


install:
  - eval "${MATRIX_EVAL}"
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh

# deploy:
#   if: env(BUILD_DOCS)="YES"
#   provider: pages
#   skip_cleanup: true
#   local_dir: docs/html
#   github_token: $GH_REPO_TOKEN
#   on:
#     branch: master