language:
  - cpp
branches:
  only:
    - master

matrix:
  fast_finish: true
  include:
    - os: osx
      osx_image: xcode10.2
      language:
        - cpp      
      addons:
        homebrew:
	  packages:
          - doxygen
          - doxygen-doc
          - doxygen-latex
          - doxygen-gui
          - graphviz
          - cmake	  
          update: true      

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master