language:
  - cpp
branches:
  only:
    - master

matrix:
  fast_finish: true
  include:
    - os: osx
      osx_image: xcode10.2
      python: 3.4
      sudo: true
  addons:
    homebrew:
      packages:
      - doxygen
      update: true

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-3.7.0-Linux-x86_64.sh -O ~/miniconda.sh
  - bash ~/miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION
  - source activate test-env