# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- windows

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: |
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe -OutFile miniconda_installer.exe
    start /wait "" miniconda_installer.exe /InstallationType=JustMe /RegisterPython=0 /S /D=%UserProfile%\Miniconda3
    conda install -c intel mkl
    conda install -c intel mkl-include
    conda install -c intel ipp
    conda install -c intel ipp-include
    mkdir build
    cd build
    cmake ..
  displayName: 'Windows VS2017 Test'
