# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- windows

pool:
  vmImage: 'windows-2019'

steps:
- script: |
    echo Downloading conda!
    powershell -command "iwr -outf miniconda_installer.exe https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe"    
    echo Installing conda!
    start /wait "" miniconda_installer.exe /InstallationType=JustMe /RegisterPython=0 /S /D=%UserProfile%\Miniconda3
    echo Conda installed!
    set PATH=%PATH%;%UserProfile%\Miniconda3\Scripts
    conda install -c intel mkl
    conda install -c intel mkl-devel    
    conda install -c intel mkl-include
    conda install -c intel ipp
    conda install -c intel ipp-devel    
    conda install -c intel ipp-include
    set MKLROOT=%UserProfile%\Miniconda3
    set IPPROOT=%UserProfile%\Miniconda3
    echo %MKLROOT%
    echo %IPPROOT%
    mkdir build
    cd build
    cmake -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DBUILD_SHARED_LIBS=TRUE ..
    echo Building and testing debug
    cmake --build . --target ALL_BUILD --config Debug
    cd Debug
    unit_tests.exe
    cd ..
    echo Building and testing release
    cmake --build . --target ALL_BUILD --config Release
    cd Release
    unit_tests.exe
  displayName: 'Windows VS2019 Test'
