# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- conan

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x' 
    addToPath: true 
    architecture: 'x86'

- script: |
    echo Downloading conda!
    powershell -command "iwr -outf miniconda_installer.exe https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe"    
    echo Installing conda!
    start /wait "" miniconda_installer.exe /InstallationType=AllUsers /RegisterPython=0 /S /D=%UserProfile%\Miniconda3
    echo Conda installed!
    set PATH=%PATH%;%UserProfile%\Miniconda3\Scripts
    echo Path set, updating conda
    conda update --yes conda
    conda install -c intel mkl --yes
    conda install -c intel mkl-static --yes
    conda install -c intel mkl-devel --yes
    conda install -c intel mkl-include --yes
    conda install -c intel ipp --yes
    conda install -c intel ipp-static     --yes
    conda install -c intel ipp-devel --yes
    conda install -c intel ipp-include --yes
    set MKLROOT=%UserProfile%\Miniconda3
    set IPPROOT=%UserProfile%\Miniconda3
    set PATH=%PATH%;%MKLROOT%\Library\bin
    set PATH=%PATH%;%IPPROOT%\Library\bin
    set PATH=%PATH%;%MKLROOT%\Library\lib
    set PATH=%PATH%;%IPPROOT%\Library\lib
    echo %MKLROOT%
    echo %IPPROOT%
    echo %PATH%
    mkdir build
    cd build
    cmake -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DBUILD_SHARED_LIBS=TRUE -G "Visual Studio 15 2017 Win64" ..
    echo Building and testing Debug
    cmake --build . --target ALL_BUILD --config Debug
    ctest -C Debug --verbose
    echo Building and testing Release
    cmake --build . --target ALL_BUILD --config Release
    ctest -C Release --verbose    
  displayName: 'Install dependencies using conda, then build and test Debug and Release using VS 2017'