# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- conan

pool:
  vmImage: 'vs2017-win2016'

variables:
    conda_path: "${env:CONDA}"

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x' 
    addToPath: true 
    architecture: 'x86'

- powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
  displayName: Add conda to PATH

- script: |
    echo ${conda_path}
    conda update conda
    conda install -c intel mkl
    conda install -c intel mkl-static
    conda install -c intel mkl-devel
    conda install -c intel mkl-include
    conda install -c intel ipp
    conda install -c intel ipp-static
    conda install -c intel ipp-devel
    conda install -c intel ipp-include
    set MKLROOT=${conda_path}
    set IPPROOT=${conda_path}
    set PATH=%PATH%;%MKLROOT%\Library\bin
    set PATH=%PATH%;%IPPROOT%\Library\bin
    set PATH=%PATH%;%MKLROOT%\Library\lib
    set PATH=%PATH%;%IPPROOT%\Library\lib
    echo %MKLROOT%
    echo %IPPROOT%
    echo %PATH%
    mkdir build
    cd build
    cmake -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DBUILD_SHARED_LIBS=TRUE -G "Visual Studio 15 2017 Win64" ..
    echo Building and testing Debug
    cmake --build . --target ALL_BUILD --config Debug
    ctest -C Debug --verbose
    echo Building and testing Release
    cmake --build . --target ALL_BUILD --config Release
    ctest -C Release --verbose    
  displayName: 'Install dependencies using conda, then build and test Debug and Release using VS 2017'